import csv

# files that are read (these are the output files generated by geocoding.py)
good_file = open('sample_good_coordinates.csv', 'r')
reader = csv.reader(good_file, delimiter = ',')

bad_file = open('sample_bad_coordinates.csv', 'r')
reader1 = csv.reader(bad_file, delimiter = ',')

no_file = open('sample_no_coordinates.csv', 'r')
reader2 = csv.reader(no_file, delimiter = ',')

# file that is written
sort_file = open('donor_info.csv', 'w', newline = '')
writer = csv.writer(sort_file)

column_titles = ["Donor ID No.", "Geocoding status", "Latitude", "Longitude"]
writer.writerow(column_titles)

# adds donor ID based on the output file it is in
for line in reader:
    good_ad = [line[0], "OK", line[1], line[2]]
    writer.writerow(good_ad)

for line in reader1:
    bad_ad = [line[0], "BAD"]
    writer.writerow(bad_ad)

for line in reader2:
    no_ad = [line[0], "NONE"]
    writer.writerow(no_ad)

good_file.close()
bad_file.close()
no_file.close()
sort_file.close()